server:
  port: 8766

#需要指明spring.application.name,这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: demo-feign
  profiles:
    active: local

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#Feign是自带断路器的，在D版本的Spring Cloud之后，它没有默认打开。需要在配置文件中配置打开它
feign:
  hystrix:
    enabled: true