server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath:/mapping/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  #  typeAliasesPackage: com.kunchi.stock.po;
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  # 配置真实数据源
spring:
  shardingsphere:
    datasource:
      names: ds1,ds2
    # 配置第 1 个数据源
      ds1:
        type: org.apache.commons.dbcp2.BasicDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://123.57.34.196:3306/ds0
        username: root
        password: 123456
    # 配置第 2 个数据源
      ds2:
        type: org.apache.commons.dbcp2.BasicDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://123.57.34.196:3306/ds1
        username: root
        password: 123456
    sharding:
      # 配置分库策略
      default-database-strategy:
        inline:
          sharding-column: user_id
          algorithm-expression: ds$->{user_id}
