spring:
  application.name: config-server
  cloud:
    config:
      #配置仓库的分支
      label: master
      server:
        git:
          #配置git仓库地址
          uri: https://github.com/Carrey-1992/Carrey-CloudConfig
          #配置仓库路径
          searchPaths: configDir
          #访问git仓库的用户名
          username:
          #访问git仓库的用户密码
          password:
    #spring.cloud.bus相关配置
    bus:
      enabled: true
      #开启消息跟踪
      trace:
        enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: bus-refresh


