server:
  port: 8001

#需要指明spring.application.name,这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: web
  profiles:
    active: local

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/