package com.carrey.demoshardingsphere.po;

public class LogEsbRequestResumeWithBLOBs extends LogEsbRequestResume {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.request_body
     *
     * @mbg.generated
     */
    private String requestBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.response_result
     *
     * @mbg.generated
     */
    private String responseResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.callback_ack_result
     *
     * @mbg.generated
     */
    private String callbackAckResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.request_body
     *
     * @return the value of log_esb_request_resume.request_body
     *
     * @mbg.generated
     */
    public String getRequestBody() {
        return requestBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.request_body
     *
     * @param requestBody the value for log_esb_request_resume.request_body
     *
     * @mbg.generated
     */
    public void setRequestBody(String requestBody) {
        this.requestBody = requestBody == null ? null : requestBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.response_result
     *
     * @return the value of log_esb_request_resume.response_result
     *
     * @mbg.generated
     */
    public String getResponseResult() {
        return responseResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.response_result
     *
     * @param responseResult the value for log_esb_request_resume.response_result
     *
     * @mbg.generated
     */
    public void setResponseResult(String responseResult) {
        this.responseResult = responseResult == null ? null : responseResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.callback_ack_result
     *
     * @return the value of log_esb_request_resume.callback_ack_result
     *
     * @mbg.generated
     */
    public String getCallbackAckResult() {
        return callbackAckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.callback_ack_result
     *
     * @param callbackAckResult the value for log_esb_request_resume.callback_ack_result
     *
     * @mbg.generated
     */
    public void setCallbackAckResult(String callbackAckResult) {
        this.callbackAckResult = callbackAckResult == null ? null : callbackAckResult.trim();
    }
}