package com.carrey.demoshardingsphere.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LogEsbRequestResumeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    public LogEsbRequestResumeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andServiceIsNull() {
            addCriterion("service is null");
            return (Criteria) this;
        }

        public Criteria andServiceIsNotNull() {
            addCriterion("service is not null");
            return (Criteria) this;
        }

        public Criteria andServiceEqualTo(String value) {
            addCriterion("service =", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceNotEqualTo(String value) {
            addCriterion("service <>", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceGreaterThan(String value) {
            addCriterion("service >", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceGreaterThanOrEqualTo(String value) {
            addCriterion("service >=", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceLessThan(String value) {
            addCriterion("service <", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceLessThanOrEqualTo(String value) {
            addCriterion("service <=", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceLike(String value) {
            addCriterion("service like", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceNotLike(String value) {
            addCriterion("service not like", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceIn(List<String> values) {
            addCriterion("service in", values, "service");
            return (Criteria) this;
        }

        public Criteria andServiceNotIn(List<String> values) {
            addCriterion("service not in", values, "service");
            return (Criteria) this;
        }

        public Criteria andServiceBetween(String value1, String value2) {
            addCriterion("service between", value1, value2, "service");
            return (Criteria) this;
        }

        public Criteria andServiceNotBetween(String value1, String value2) {
            addCriterion("service not between", value1, value2, "service");
            return (Criteria) this;
        }

        public Criteria andModularIsNull() {
            addCriterion("modular is null");
            return (Criteria) this;
        }

        public Criteria andModularIsNotNull() {
            addCriterion("modular is not null");
            return (Criteria) this;
        }

        public Criteria andModularEqualTo(String value) {
            addCriterion("modular =", value, "modular");
            return (Criteria) this;
        }

        public Criteria andModularNotEqualTo(String value) {
            addCriterion("modular <>", value, "modular");
            return (Criteria) this;
        }

        public Criteria andModularGreaterThan(String value) {
            addCriterion("modular >", value, "modular");
            return (Criteria) this;
        }

        public Criteria andModularGreaterThanOrEqualTo(String value) {
            addCriterion("modular >=", value, "modular");
            return (Criteria) this;
        }

        public Criteria andModularLessThan(String value) {
            addCriterion("modular <", value, "modular");
            return (Criteria) this;
        }

        public Criteria andModularLessThanOrEqualTo(String value) {
            addCriterion("modular <=", value, "modular");
            return (Criteria) this;
        }

        public Criteria andModularLike(String value) {
            addCriterion("modular like", value, "modular");
            return (Criteria) this;
        }

        public Criteria andModularNotLike(String value) {
            addCriterion("modular not like", value, "modular");
            return (Criteria) this;
        }

        public Criteria andModularIn(List<String> values) {
            addCriterion("modular in", values, "modular");
            return (Criteria) this;
        }

        public Criteria andModularNotIn(List<String> values) {
            addCriterion("modular not in", values, "modular");
            return (Criteria) this;
        }

        public Criteria andModularBetween(String value1, String value2) {
            addCriterion("modular between", value1, value2, "modular");
            return (Criteria) this;
        }

        public Criteria andModularNotBetween(String value1, String value2) {
            addCriterion("modular not between", value1, value2, "modular");
            return (Criteria) this;
        }

        public Criteria andModularKeyIsNull() {
            addCriterion("modular_key is null");
            return (Criteria) this;
        }

        public Criteria andModularKeyIsNotNull() {
            addCriterion("modular_key is not null");
            return (Criteria) this;
        }

        public Criteria andModularKeyEqualTo(String value) {
            addCriterion("modular_key =", value, "modularKey");
            return (Criteria) this;
        }

        public Criteria andModularKeyNotEqualTo(String value) {
            addCriterion("modular_key <>", value, "modularKey");
            return (Criteria) this;
        }

        public Criteria andModularKeyGreaterThan(String value) {
            addCriterion("modular_key >", value, "modularKey");
            return (Criteria) this;
        }

        public Criteria andModularKeyGreaterThanOrEqualTo(String value) {
            addCriterion("modular_key >=", value, "modularKey");
            return (Criteria) this;
        }

        public Criteria andModularKeyLessThan(String value) {
            addCriterion("modular_key <", value, "modularKey");
            return (Criteria) this;
        }

        public Criteria andModularKeyLessThanOrEqualTo(String value) {
            addCriterion("modular_key <=", value, "modularKey");
            return (Criteria) this;
        }

        public Criteria andModularKeyLike(String value) {
            addCriterion("modular_key like", value, "modularKey");
            return (Criteria) this;
        }

        public Criteria andModularKeyNotLike(String value) {
            addCriterion("modular_key not like", value, "modularKey");
            return (Criteria) this;
        }

        public Criteria andModularKeyIn(List<String> values) {
            addCriterion("modular_key in", values, "modularKey");
            return (Criteria) this;
        }

        public Criteria andModularKeyNotIn(List<String> values) {
            addCriterion("modular_key not in", values, "modularKey");
            return (Criteria) this;
        }

        public Criteria andModularKeyBetween(String value1, String value2) {
            addCriterion("modular_key between", value1, value2, "modularKey");
            return (Criteria) this;
        }

        public Criteria andModularKeyNotBetween(String value1, String value2) {
            addCriterion("modular_key not between", value1, value2, "modularKey");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIsNull() {
            addCriterion("operate_type is null");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIsNotNull() {
            addCriterion("operate_type is not null");
            return (Criteria) this;
        }

        public Criteria andOperateTypeEqualTo(Integer value) {
            addCriterion("operate_type =", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotEqualTo(Integer value) {
            addCriterion("operate_type <>", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeGreaterThan(Integer value) {
            addCriterion("operate_type >", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("operate_type >=", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLessThan(Integer value) {
            addCriterion("operate_type <", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLessThanOrEqualTo(Integer value) {
            addCriterion("operate_type <=", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIn(List<Integer> values) {
            addCriterion("operate_type in", values, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotIn(List<Integer> values) {
            addCriterion("operate_type not in", values, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeBetween(Integer value1, Integer value2) {
            addCriterion("operate_type between", value1, value2, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("operate_type not between", value1, value2, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateDescIsNull() {
            addCriterion("operate_desc is null");
            return (Criteria) this;
        }

        public Criteria andOperateDescIsNotNull() {
            addCriterion("operate_desc is not null");
            return (Criteria) this;
        }

        public Criteria andOperateDescEqualTo(String value) {
            addCriterion("operate_desc =", value, "operateDesc");
            return (Criteria) this;
        }

        public Criteria andOperateDescNotEqualTo(String value) {
            addCriterion("operate_desc <>", value, "operateDesc");
            return (Criteria) this;
        }

        public Criteria andOperateDescGreaterThan(String value) {
            addCriterion("operate_desc >", value, "operateDesc");
            return (Criteria) this;
        }

        public Criteria andOperateDescGreaterThanOrEqualTo(String value) {
            addCriterion("operate_desc >=", value, "operateDesc");
            return (Criteria) this;
        }

        public Criteria andOperateDescLessThan(String value) {
            addCriterion("operate_desc <", value, "operateDesc");
            return (Criteria) this;
        }

        public Criteria andOperateDescLessThanOrEqualTo(String value) {
            addCriterion("operate_desc <=", value, "operateDesc");
            return (Criteria) this;
        }

        public Criteria andOperateDescLike(String value) {
            addCriterion("operate_desc like", value, "operateDesc");
            return (Criteria) this;
        }

        public Criteria andOperateDescNotLike(String value) {
            addCriterion("operate_desc not like", value, "operateDesc");
            return (Criteria) this;
        }

        public Criteria andOperateDescIn(List<String> values) {
            addCriterion("operate_desc in", values, "operateDesc");
            return (Criteria) this;
        }

        public Criteria andOperateDescNotIn(List<String> values) {
            addCriterion("operate_desc not in", values, "operateDesc");
            return (Criteria) this;
        }

        public Criteria andOperateDescBetween(String value1, String value2) {
            addCriterion("operate_desc between", value1, value2, "operateDesc");
            return (Criteria) this;
        }

        public Criteria andOperateDescNotBetween(String value1, String value2) {
            addCriterion("operate_desc not between", value1, value2, "operateDesc");
            return (Criteria) this;
        }

        public Criteria andRequestIdIsNull() {
            addCriterion("request_id is null");
            return (Criteria) this;
        }

        public Criteria andRequestIdIsNotNull() {
            addCriterion("request_id is not null");
            return (Criteria) this;
        }

        public Criteria andRequestIdEqualTo(String value) {
            addCriterion("request_id =", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotEqualTo(String value) {
            addCriterion("request_id <>", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdGreaterThan(String value) {
            addCriterion("request_id >", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdGreaterThanOrEqualTo(String value) {
            addCriterion("request_id >=", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdLessThan(String value) {
            addCriterion("request_id <", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdLessThanOrEqualTo(String value) {
            addCriterion("request_id <=", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdLike(String value) {
            addCriterion("request_id like", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotLike(String value) {
            addCriterion("request_id not like", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdIn(List<String> values) {
            addCriterion("request_id in", values, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotIn(List<String> values) {
            addCriterion("request_id not in", values, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdBetween(String value1, String value2) {
            addCriterion("request_id between", value1, value2, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotBetween(String value1, String value2) {
            addCriterion("request_id not between", value1, value2, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestTypeIsNull() {
            addCriterion("request_type is null");
            return (Criteria) this;
        }

        public Criteria andRequestTypeIsNotNull() {
            addCriterion("request_type is not null");
            return (Criteria) this;
        }

        public Criteria andRequestTypeEqualTo(Integer value) {
            addCriterion("request_type =", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeNotEqualTo(Integer value) {
            addCriterion("request_type <>", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeGreaterThan(Integer value) {
            addCriterion("request_type >", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("request_type >=", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeLessThan(Integer value) {
            addCriterion("request_type <", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeLessThanOrEqualTo(Integer value) {
            addCriterion("request_type <=", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeIn(List<Integer> values) {
            addCriterion("request_type in", values, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeNotIn(List<Integer> values) {
            addCriterion("request_type not in", values, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeBetween(Integer value1, Integer value2) {
            addCriterion("request_type between", value1, value2, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("request_type not between", value1, value2, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestParamIsNull() {
            addCriterion("request_param is null");
            return (Criteria) this;
        }

        public Criteria andRequestParamIsNotNull() {
            addCriterion("request_param is not null");
            return (Criteria) this;
        }

        public Criteria andRequestParamEqualTo(String value) {
            addCriterion("request_param =", value, "requestParam");
            return (Criteria) this;
        }

        public Criteria andRequestParamNotEqualTo(String value) {
            addCriterion("request_param <>", value, "requestParam");
            return (Criteria) this;
        }

        public Criteria andRequestParamGreaterThan(String value) {
            addCriterion("request_param >", value, "requestParam");
            return (Criteria) this;
        }

        public Criteria andRequestParamGreaterThanOrEqualTo(String value) {
            addCriterion("request_param >=", value, "requestParam");
            return (Criteria) this;
        }

        public Criteria andRequestParamLessThan(String value) {
            addCriterion("request_param <", value, "requestParam");
            return (Criteria) this;
        }

        public Criteria andRequestParamLessThanOrEqualTo(String value) {
            addCriterion("request_param <=", value, "requestParam");
            return (Criteria) this;
        }

        public Criteria andRequestParamLike(String value) {
            addCriterion("request_param like", value, "requestParam");
            return (Criteria) this;
        }

        public Criteria andRequestParamNotLike(String value) {
            addCriterion("request_param not like", value, "requestParam");
            return (Criteria) this;
        }

        public Criteria andRequestParamIn(List<String> values) {
            addCriterion("request_param in", values, "requestParam");
            return (Criteria) this;
        }

        public Criteria andRequestParamNotIn(List<String> values) {
            addCriterion("request_param not in", values, "requestParam");
            return (Criteria) this;
        }

        public Criteria andRequestParamBetween(String value1, String value2) {
            addCriterion("request_param between", value1, value2, "requestParam");
            return (Criteria) this;
        }

        public Criteria andRequestParamNotBetween(String value1, String value2) {
            addCriterion("request_param not between", value1, value2, "requestParam");
            return (Criteria) this;
        }

        public Criteria andRequestUrlIsNull() {
            addCriterion("request_url is null");
            return (Criteria) this;
        }

        public Criteria andRequestUrlIsNotNull() {
            addCriterion("request_url is not null");
            return (Criteria) this;
        }

        public Criteria andRequestUrlEqualTo(String value) {
            addCriterion("request_url =", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotEqualTo(String value) {
            addCriterion("request_url <>", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlGreaterThan(String value) {
            addCriterion("request_url >", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlGreaterThanOrEqualTo(String value) {
            addCriterion("request_url >=", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlLessThan(String value) {
            addCriterion("request_url <", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlLessThanOrEqualTo(String value) {
            addCriterion("request_url <=", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlLike(String value) {
            addCriterion("request_url like", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotLike(String value) {
            addCriterion("request_url not like", value, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlIn(List<String> values) {
            addCriterion("request_url in", values, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotIn(List<String> values) {
            addCriterion("request_url not in", values, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlBetween(String value1, String value2) {
            addCriterion("request_url between", value1, value2, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andRequestUrlNotBetween(String value1, String value2) {
            addCriterion("request_url not between", value1, value2, "requestUrl");
            return (Criteria) this;
        }

        public Criteria andMsgIdIsNull() {
            addCriterion("msg_id is null");
            return (Criteria) this;
        }

        public Criteria andMsgIdIsNotNull() {
            addCriterion("msg_id is not null");
            return (Criteria) this;
        }

        public Criteria andMsgIdEqualTo(String value) {
            addCriterion("msg_id =", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdNotEqualTo(String value) {
            addCriterion("msg_id <>", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdGreaterThan(String value) {
            addCriterion("msg_id >", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdGreaterThanOrEqualTo(String value) {
            addCriterion("msg_id >=", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdLessThan(String value) {
            addCriterion("msg_id <", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdLessThanOrEqualTo(String value) {
            addCriterion("msg_id <=", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdLike(String value) {
            addCriterion("msg_id like", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdNotLike(String value) {
            addCriterion("msg_id not like", value, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdIn(List<String> values) {
            addCriterion("msg_id in", values, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdNotIn(List<String> values) {
            addCriterion("msg_id not in", values, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdBetween(String value1, String value2) {
            addCriterion("msg_id between", value1, value2, "msgId");
            return (Criteria) this;
        }

        public Criteria andMsgIdNotBetween(String value1, String value2) {
            addCriterion("msg_id not between", value1, value2, "msgId");
            return (Criteria) this;
        }

        public Criteria andIsReqSuccessIsNull() {
            addCriterion("is_req_success is null");
            return (Criteria) this;
        }

        public Criteria andIsReqSuccessIsNotNull() {
            addCriterion("is_req_success is not null");
            return (Criteria) this;
        }

        public Criteria andIsReqSuccessEqualTo(Boolean value) {
            addCriterion("is_req_success =", value, "isReqSuccess");
            return (Criteria) this;
        }

        public Criteria andIsReqSuccessNotEqualTo(Boolean value) {
            addCriterion("is_req_success <>", value, "isReqSuccess");
            return (Criteria) this;
        }

        public Criteria andIsReqSuccessGreaterThan(Boolean value) {
            addCriterion("is_req_success >", value, "isReqSuccess");
            return (Criteria) this;
        }

        public Criteria andIsReqSuccessGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_req_success >=", value, "isReqSuccess");
            return (Criteria) this;
        }

        public Criteria andIsReqSuccessLessThan(Boolean value) {
            addCriterion("is_req_success <", value, "isReqSuccess");
            return (Criteria) this;
        }

        public Criteria andIsReqSuccessLessThanOrEqualTo(Boolean value) {
            addCriterion("is_req_success <=", value, "isReqSuccess");
            return (Criteria) this;
        }

        public Criteria andIsReqSuccessIn(List<Boolean> values) {
            addCriterion("is_req_success in", values, "isReqSuccess");
            return (Criteria) this;
        }

        public Criteria andIsReqSuccessNotIn(List<Boolean> values) {
            addCriterion("is_req_success not in", values, "isReqSuccess");
            return (Criteria) this;
        }

        public Criteria andIsReqSuccessBetween(Boolean value1, Boolean value2) {
            addCriterion("is_req_success between", value1, value2, "isReqSuccess");
            return (Criteria) this;
        }

        public Criteria andIsReqSuccessNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_req_success not between", value1, value2, "isReqSuccess");
            return (Criteria) this;
        }

        public Criteria andIsNeedCallbackAckIsNull() {
            addCriterion("is_need_callback_ack is null");
            return (Criteria) this;
        }

        public Criteria andIsNeedCallbackAckIsNotNull() {
            addCriterion("is_need_callback_ack is not null");
            return (Criteria) this;
        }

        public Criteria andIsNeedCallbackAckEqualTo(Boolean value) {
            addCriterion("is_need_callback_ack =", value, "isNeedCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsNeedCallbackAckNotEqualTo(Boolean value) {
            addCriterion("is_need_callback_ack <>", value, "isNeedCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsNeedCallbackAckGreaterThan(Boolean value) {
            addCriterion("is_need_callback_ack >", value, "isNeedCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsNeedCallbackAckGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_need_callback_ack >=", value, "isNeedCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsNeedCallbackAckLessThan(Boolean value) {
            addCriterion("is_need_callback_ack <", value, "isNeedCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsNeedCallbackAckLessThanOrEqualTo(Boolean value) {
            addCriterion("is_need_callback_ack <=", value, "isNeedCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsNeedCallbackAckIn(List<Boolean> values) {
            addCriterion("is_need_callback_ack in", values, "isNeedCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsNeedCallbackAckNotIn(List<Boolean> values) {
            addCriterion("is_need_callback_ack not in", values, "isNeedCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsNeedCallbackAckBetween(Boolean value1, Boolean value2) {
            addCriterion("is_need_callback_ack between", value1, value2, "isNeedCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsNeedCallbackAckNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_need_callback_ack not between", value1, value2, "isNeedCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckIsNull() {
            addCriterion("is_callback_ack is null");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckIsNotNull() {
            addCriterion("is_callback_ack is not null");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckEqualTo(Boolean value) {
            addCriterion("is_callback_ack =", value, "isCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckNotEqualTo(Boolean value) {
            addCriterion("is_callback_ack <>", value, "isCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckGreaterThan(Boolean value) {
            addCriterion("is_callback_ack >", value, "isCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_callback_ack >=", value, "isCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckLessThan(Boolean value) {
            addCriterion("is_callback_ack <", value, "isCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckLessThanOrEqualTo(Boolean value) {
            addCriterion("is_callback_ack <=", value, "isCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckIn(List<Boolean> values) {
            addCriterion("is_callback_ack in", values, "isCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckNotIn(List<Boolean> values) {
            addCriterion("is_callback_ack not in", values, "isCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckBetween(Boolean value1, Boolean value2) {
            addCriterion("is_callback_ack between", value1, value2, "isCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_callback_ack not between", value1, value2, "isCallbackAck");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckSuccessIsNull() {
            addCriterion("is_callback_ack_success is null");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckSuccessIsNotNull() {
            addCriterion("is_callback_ack_success is not null");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckSuccessEqualTo(Boolean value) {
            addCriterion("is_callback_ack_success =", value, "isCallbackAckSuccess");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckSuccessNotEqualTo(Boolean value) {
            addCriterion("is_callback_ack_success <>", value, "isCallbackAckSuccess");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckSuccessGreaterThan(Boolean value) {
            addCriterion("is_callback_ack_success >", value, "isCallbackAckSuccess");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckSuccessGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_callback_ack_success >=", value, "isCallbackAckSuccess");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckSuccessLessThan(Boolean value) {
            addCriterion("is_callback_ack_success <", value, "isCallbackAckSuccess");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckSuccessLessThanOrEqualTo(Boolean value) {
            addCriterion("is_callback_ack_success <=", value, "isCallbackAckSuccess");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckSuccessIn(List<Boolean> values) {
            addCriterion("is_callback_ack_success in", values, "isCallbackAckSuccess");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckSuccessNotIn(List<Boolean> values) {
            addCriterion("is_callback_ack_success not in", values, "isCallbackAckSuccess");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckSuccessBetween(Boolean value1, Boolean value2) {
            addCriterion("is_callback_ack_success between", value1, value2, "isCallbackAckSuccess");
            return (Criteria) this;
        }

        public Criteria andIsCallbackAckSuccessNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_callback_ack_success not between", value1, value2, "isCallbackAckSuccess");
            return (Criteria) this;
        }

        public Criteria andCallbackAckDateIsNull() {
            addCriterion("callback_ack_date is null");
            return (Criteria) this;
        }

        public Criteria andCallbackAckDateIsNotNull() {
            addCriterion("callback_ack_date is not null");
            return (Criteria) this;
        }

        public Criteria andCallbackAckDateEqualTo(Date value) {
            addCriterion("callback_ack_date =", value, "callbackAckDate");
            return (Criteria) this;
        }

        public Criteria andCallbackAckDateNotEqualTo(Date value) {
            addCriterion("callback_ack_date <>", value, "callbackAckDate");
            return (Criteria) this;
        }

        public Criteria andCallbackAckDateGreaterThan(Date value) {
            addCriterion("callback_ack_date >", value, "callbackAckDate");
            return (Criteria) this;
        }

        public Criteria andCallbackAckDateGreaterThanOrEqualTo(Date value) {
            addCriterion("callback_ack_date >=", value, "callbackAckDate");
            return (Criteria) this;
        }

        public Criteria andCallbackAckDateLessThan(Date value) {
            addCriterion("callback_ack_date <", value, "callbackAckDate");
            return (Criteria) this;
        }

        public Criteria andCallbackAckDateLessThanOrEqualTo(Date value) {
            addCriterion("callback_ack_date <=", value, "callbackAckDate");
            return (Criteria) this;
        }

        public Criteria andCallbackAckDateIn(List<Date> values) {
            addCriterion("callback_ack_date in", values, "callbackAckDate");
            return (Criteria) this;
        }

        public Criteria andCallbackAckDateNotIn(List<Date> values) {
            addCriterion("callback_ack_date not in", values, "callbackAckDate");
            return (Criteria) this;
        }

        public Criteria andCallbackAckDateBetween(Date value1, Date value2) {
            addCriterion("callback_ack_date between", value1, value2, "callbackAckDate");
            return (Criteria) this;
        }

        public Criteria andCallbackAckDateNotBetween(Date value1, Date value2) {
            addCriterion("callback_ack_date not between", value1, value2, "callbackAckDate");
            return (Criteria) this;
        }

        public Criteria andCallbackAckUrlIsNull() {
            addCriterion("callback_ack_url is null");
            return (Criteria) this;
        }

        public Criteria andCallbackAckUrlIsNotNull() {
            addCriterion("callback_ack_url is not null");
            return (Criteria) this;
        }

        public Criteria andCallbackAckUrlEqualTo(String value) {
            addCriterion("callback_ack_url =", value, "callbackAckUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackAckUrlNotEqualTo(String value) {
            addCriterion("callback_ack_url <>", value, "callbackAckUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackAckUrlGreaterThan(String value) {
            addCriterion("callback_ack_url >", value, "callbackAckUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackAckUrlGreaterThanOrEqualTo(String value) {
            addCriterion("callback_ack_url >=", value, "callbackAckUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackAckUrlLessThan(String value) {
            addCriterion("callback_ack_url <", value, "callbackAckUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackAckUrlLessThanOrEqualTo(String value) {
            addCriterion("callback_ack_url <=", value, "callbackAckUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackAckUrlLike(String value) {
            addCriterion("callback_ack_url like", value, "callbackAckUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackAckUrlNotLike(String value) {
            addCriterion("callback_ack_url not like", value, "callbackAckUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackAckUrlIn(List<String> values) {
            addCriterion("callback_ack_url in", values, "callbackAckUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackAckUrlNotIn(List<String> values) {
            addCriterion("callback_ack_url not in", values, "callbackAckUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackAckUrlBetween(String value1, String value2) {
            addCriterion("callback_ack_url between", value1, value2, "callbackAckUrl");
            return (Criteria) this;
        }

        public Criteria andCallbackAckUrlNotBetween(String value1, String value2) {
            addCriterion("callback_ack_url not between", value1, value2, "callbackAckUrl");
            return (Criteria) this;
        }

        public Criteria andIsNeedAutoRetryIsNull() {
            addCriterion("is_need_auto_retry is null");
            return (Criteria) this;
        }

        public Criteria andIsNeedAutoRetryIsNotNull() {
            addCriterion("is_need_auto_retry is not null");
            return (Criteria) this;
        }

        public Criteria andIsNeedAutoRetryEqualTo(Boolean value) {
            addCriterion("is_need_auto_retry =", value, "isNeedAutoRetry");
            return (Criteria) this;
        }

        public Criteria andIsNeedAutoRetryNotEqualTo(Boolean value) {
            addCriterion("is_need_auto_retry <>", value, "isNeedAutoRetry");
            return (Criteria) this;
        }

        public Criteria andIsNeedAutoRetryGreaterThan(Boolean value) {
            addCriterion("is_need_auto_retry >", value, "isNeedAutoRetry");
            return (Criteria) this;
        }

        public Criteria andIsNeedAutoRetryGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_need_auto_retry >=", value, "isNeedAutoRetry");
            return (Criteria) this;
        }

        public Criteria andIsNeedAutoRetryLessThan(Boolean value) {
            addCriterion("is_need_auto_retry <", value, "isNeedAutoRetry");
            return (Criteria) this;
        }

        public Criteria andIsNeedAutoRetryLessThanOrEqualTo(Boolean value) {
            addCriterion("is_need_auto_retry <=", value, "isNeedAutoRetry");
            return (Criteria) this;
        }

        public Criteria andIsNeedAutoRetryIn(List<Boolean> values) {
            addCriterion("is_need_auto_retry in", values, "isNeedAutoRetry");
            return (Criteria) this;
        }

        public Criteria andIsNeedAutoRetryNotIn(List<Boolean> values) {
            addCriterion("is_need_auto_retry not in", values, "isNeedAutoRetry");
            return (Criteria) this;
        }

        public Criteria andIsNeedAutoRetryBetween(Boolean value1, Boolean value2) {
            addCriterion("is_need_auto_retry between", value1, value2, "isNeedAutoRetry");
            return (Criteria) this;
        }

        public Criteria andIsNeedAutoRetryNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_need_auto_retry not between", value1, value2, "isNeedAutoRetry");
            return (Criteria) this;
        }

        public Criteria andRetryTypeIsNull() {
            addCriterion("retry_type is null");
            return (Criteria) this;
        }

        public Criteria andRetryTypeIsNotNull() {
            addCriterion("retry_type is not null");
            return (Criteria) this;
        }

        public Criteria andRetryTypeEqualTo(Integer value) {
            addCriterion("retry_type =", value, "retryType");
            return (Criteria) this;
        }

        public Criteria andRetryTypeNotEqualTo(Integer value) {
            addCriterion("retry_type <>", value, "retryType");
            return (Criteria) this;
        }

        public Criteria andRetryTypeGreaterThan(Integer value) {
            addCriterion("retry_type >", value, "retryType");
            return (Criteria) this;
        }

        public Criteria andRetryTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("retry_type >=", value, "retryType");
            return (Criteria) this;
        }

        public Criteria andRetryTypeLessThan(Integer value) {
            addCriterion("retry_type <", value, "retryType");
            return (Criteria) this;
        }

        public Criteria andRetryTypeLessThanOrEqualTo(Integer value) {
            addCriterion("retry_type <=", value, "retryType");
            return (Criteria) this;
        }

        public Criteria andRetryTypeIn(List<Integer> values) {
            addCriterion("retry_type in", values, "retryType");
            return (Criteria) this;
        }

        public Criteria andRetryTypeNotIn(List<Integer> values) {
            addCriterion("retry_type not in", values, "retryType");
            return (Criteria) this;
        }

        public Criteria andRetryTypeBetween(Integer value1, Integer value2) {
            addCriterion("retry_type between", value1, value2, "retryType");
            return (Criteria) this;
        }

        public Criteria andRetryTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("retry_type not between", value1, value2, "retryType");
            return (Criteria) this;
        }

        public Criteria andIsRetryingIsNull() {
            addCriterion("is_retrying is null");
            return (Criteria) this;
        }

        public Criteria andIsRetryingIsNotNull() {
            addCriterion("is_retrying is not null");
            return (Criteria) this;
        }

        public Criteria andIsRetryingEqualTo(Boolean value) {
            addCriterion("is_retrying =", value, "isRetrying");
            return (Criteria) this;
        }

        public Criteria andIsRetryingNotEqualTo(Boolean value) {
            addCriterion("is_retrying <>", value, "isRetrying");
            return (Criteria) this;
        }

        public Criteria andIsRetryingGreaterThan(Boolean value) {
            addCriterion("is_retrying >", value, "isRetrying");
            return (Criteria) this;
        }

        public Criteria andIsRetryingGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_retrying >=", value, "isRetrying");
            return (Criteria) this;
        }

        public Criteria andIsRetryingLessThan(Boolean value) {
            addCriterion("is_retrying <", value, "isRetrying");
            return (Criteria) this;
        }

        public Criteria andIsRetryingLessThanOrEqualTo(Boolean value) {
            addCriterion("is_retrying <=", value, "isRetrying");
            return (Criteria) this;
        }

        public Criteria andIsRetryingIn(List<Boolean> values) {
            addCriterion("is_retrying in", values, "isRetrying");
            return (Criteria) this;
        }

        public Criteria andIsRetryingNotIn(List<Boolean> values) {
            addCriterion("is_retrying not in", values, "isRetrying");
            return (Criteria) this;
        }

        public Criteria andIsRetryingBetween(Boolean value1, Boolean value2) {
            addCriterion("is_retrying between", value1, value2, "isRetrying");
            return (Criteria) this;
        }

        public Criteria andIsRetryingNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_retrying not between", value1, value2, "isRetrying");
            return (Criteria) this;
        }

        public Criteria andIsRetrySuccessIsNull() {
            addCriterion("is_retry_success is null");
            return (Criteria) this;
        }

        public Criteria andIsRetrySuccessIsNotNull() {
            addCriterion("is_retry_success is not null");
            return (Criteria) this;
        }

        public Criteria andIsRetrySuccessEqualTo(Boolean value) {
            addCriterion("is_retry_success =", value, "isRetrySuccess");
            return (Criteria) this;
        }

        public Criteria andIsRetrySuccessNotEqualTo(Boolean value) {
            addCriterion("is_retry_success <>", value, "isRetrySuccess");
            return (Criteria) this;
        }

        public Criteria andIsRetrySuccessGreaterThan(Boolean value) {
            addCriterion("is_retry_success >", value, "isRetrySuccess");
            return (Criteria) this;
        }

        public Criteria andIsRetrySuccessGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_retry_success >=", value, "isRetrySuccess");
            return (Criteria) this;
        }

        public Criteria andIsRetrySuccessLessThan(Boolean value) {
            addCriterion("is_retry_success <", value, "isRetrySuccess");
            return (Criteria) this;
        }

        public Criteria andIsRetrySuccessLessThanOrEqualTo(Boolean value) {
            addCriterion("is_retry_success <=", value, "isRetrySuccess");
            return (Criteria) this;
        }

        public Criteria andIsRetrySuccessIn(List<Boolean> values) {
            addCriterion("is_retry_success in", values, "isRetrySuccess");
            return (Criteria) this;
        }

        public Criteria andIsRetrySuccessNotIn(List<Boolean> values) {
            addCriterion("is_retry_success not in", values, "isRetrySuccess");
            return (Criteria) this;
        }

        public Criteria andIsRetrySuccessBetween(Boolean value1, Boolean value2) {
            addCriterion("is_retry_success between", value1, value2, "isRetrySuccess");
            return (Criteria) this;
        }

        public Criteria andIsRetrySuccessNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_retry_success not between", value1, value2, "isRetrySuccess");
            return (Criteria) this;
        }

        public Criteria andRetryNumIsNull() {
            addCriterion("retry_num is null");
            return (Criteria) this;
        }

        public Criteria andRetryNumIsNotNull() {
            addCriterion("retry_num is not null");
            return (Criteria) this;
        }

        public Criteria andRetryNumEqualTo(Integer value) {
            addCriterion("retry_num =", value, "retryNum");
            return (Criteria) this;
        }

        public Criteria andRetryNumNotEqualTo(Integer value) {
            addCriterion("retry_num <>", value, "retryNum");
            return (Criteria) this;
        }

        public Criteria andRetryNumGreaterThan(Integer value) {
            addCriterion("retry_num >", value, "retryNum");
            return (Criteria) this;
        }

        public Criteria andRetryNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("retry_num >=", value, "retryNum");
            return (Criteria) this;
        }

        public Criteria andRetryNumLessThan(Integer value) {
            addCriterion("retry_num <", value, "retryNum");
            return (Criteria) this;
        }

        public Criteria andRetryNumLessThanOrEqualTo(Integer value) {
            addCriterion("retry_num <=", value, "retryNum");
            return (Criteria) this;
        }

        public Criteria andRetryNumIn(List<Integer> values) {
            addCriterion("retry_num in", values, "retryNum");
            return (Criteria) this;
        }

        public Criteria andRetryNumNotIn(List<Integer> values) {
            addCriterion("retry_num not in", values, "retryNum");
            return (Criteria) this;
        }

        public Criteria andRetryNumBetween(Integer value1, Integer value2) {
            addCriterion("retry_num between", value1, value2, "retryNum");
            return (Criteria) this;
        }

        public Criteria andRetryNumNotBetween(Integer value1, Integer value2) {
            addCriterion("retry_num not between", value1, value2, "retryNum");
            return (Criteria) this;
        }

        public Criteria andEnableStateIsNull() {
            addCriterion("enable_state is null");
            return (Criteria) this;
        }

        public Criteria andEnableStateIsNotNull() {
            addCriterion("enable_state is not null");
            return (Criteria) this;
        }

        public Criteria andEnableStateEqualTo(Integer value) {
            addCriterion("enable_state =", value, "enableState");
            return (Criteria) this;
        }

        public Criteria andEnableStateNotEqualTo(Integer value) {
            addCriterion("enable_state <>", value, "enableState");
            return (Criteria) this;
        }

        public Criteria andEnableStateGreaterThan(Integer value) {
            addCriterion("enable_state >", value, "enableState");
            return (Criteria) this;
        }

        public Criteria andEnableStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("enable_state >=", value, "enableState");
            return (Criteria) this;
        }

        public Criteria andEnableStateLessThan(Integer value) {
            addCriterion("enable_state <", value, "enableState");
            return (Criteria) this;
        }

        public Criteria andEnableStateLessThanOrEqualTo(Integer value) {
            addCriterion("enable_state <=", value, "enableState");
            return (Criteria) this;
        }

        public Criteria andEnableStateIn(List<Integer> values) {
            addCriterion("enable_state in", values, "enableState");
            return (Criteria) this;
        }

        public Criteria andEnableStateNotIn(List<Integer> values) {
            addCriterion("enable_state not in", values, "enableState");
            return (Criteria) this;
        }

        public Criteria andEnableStateBetween(Integer value1, Integer value2) {
            addCriterion("enable_state between", value1, value2, "enableState");
            return (Criteria) this;
        }

        public Criteria andEnableStateNotBetween(Integer value1, Integer value2) {
            addCriterion("enable_state not between", value1, value2, "enableState");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}