package com.carrey.demoshardingsphere.po;

import java.util.Date;

public class LogEsbRequestResume {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.service
     *
     * @mbg.generated
     */
    private String service;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.modular
     *
     * @mbg.generated
     */
    private String modular;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.modular_key
     *
     * @mbg.generated
     */
    private String modularKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.operate_type
     *
     * @mbg.generated
     */
    private Integer operateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.operate_desc
     *
     * @mbg.generated
     */
    private String operateDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.request_id
     *
     * @mbg.generated
     */
    private String requestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.request_type
     *
     * @mbg.generated
     */
    private Byte requestType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.request_param
     *
     * @mbg.generated
     */
    private String requestParam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.request_url
     *
     * @mbg.generated
     */
    private String requestUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.msg_id
     *
     * @mbg.generated
     */
    private String msgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.is_req_success
     *
     * @mbg.generated
     */
    private Byte isReqSuccess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.is_need_callback_ack
     *
     * @mbg.generated
     */
    private Byte isNeedCallbackAck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.is_callback_ack
     *
     * @mbg.generated
     */
    private Byte isCallbackAck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.is_callback_ack_success
     *
     * @mbg.generated
     */
    private Byte isCallbackAckSuccess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.callback_ack_date
     *
     * @mbg.generated
     */
    private Date callbackAckDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.callback_ack_url
     *
     * @mbg.generated
     */
    private String callbackAckUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.is_need_auto_retry
     *
     * @mbg.generated
     */
    private Byte isNeedAutoRetry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.retry_type
     *
     * @mbg.generated
     */
    private Byte retryType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.is_retrying
     *
     * @mbg.generated
     */
    private Byte isRetrying;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.is_retry_success
     *
     * @mbg.generated
     */
    private Byte isRetrySuccess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.retry_num
     *
     * @mbg.generated
     */
    private Integer retryNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_esb_request_resume.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.id
     *
     * @return the value of log_esb_request_resume.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.id
     *
     * @param id the value for log_esb_request_resume.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.user_id
     *
     * @return the value of log_esb_request_resume.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.user_id
     *
     * @param userId the value for log_esb_request_resume.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.service
     *
     * @return the value of log_esb_request_resume.service
     *
     * @mbg.generated
     */
    public String getService() {
        return service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.service
     *
     * @param service the value for log_esb_request_resume.service
     *
     * @mbg.generated
     */
    public void setService(String service) {
        this.service = service == null ? null : service.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.modular
     *
     * @return the value of log_esb_request_resume.modular
     *
     * @mbg.generated
     */
    public String getModular() {
        return modular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.modular
     *
     * @param modular the value for log_esb_request_resume.modular
     *
     * @mbg.generated
     */
    public void setModular(String modular) {
        this.modular = modular == null ? null : modular.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.modular_key
     *
     * @return the value of log_esb_request_resume.modular_key
     *
     * @mbg.generated
     */
    public String getModularKey() {
        return modularKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.modular_key
     *
     * @param modularKey the value for log_esb_request_resume.modular_key
     *
     * @mbg.generated
     */
    public void setModularKey(String modularKey) {
        this.modularKey = modularKey == null ? null : modularKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.operate_type
     *
     * @return the value of log_esb_request_resume.operate_type
     *
     * @mbg.generated
     */
    public Integer getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.operate_type
     *
     * @param operateType the value for log_esb_request_resume.operate_type
     *
     * @mbg.generated
     */
    public void setOperateType(Integer operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.operate_desc
     *
     * @return the value of log_esb_request_resume.operate_desc
     *
     * @mbg.generated
     */
    public String getOperateDesc() {
        return operateDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.operate_desc
     *
     * @param operateDesc the value for log_esb_request_resume.operate_desc
     *
     * @mbg.generated
     */
    public void setOperateDesc(String operateDesc) {
        this.operateDesc = operateDesc == null ? null : operateDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.request_id
     *
     * @return the value of log_esb_request_resume.request_id
     *
     * @mbg.generated
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.request_id
     *
     * @param requestId the value for log_esb_request_resume.request_id
     *
     * @mbg.generated
     */
    public void setRequestId(String requestId) {
        this.requestId = requestId == null ? null : requestId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.request_type
     *
     * @return the value of log_esb_request_resume.request_type
     *
     * @mbg.generated
     */
    public Byte getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.request_type
     *
     * @param requestType the value for log_esb_request_resume.request_type
     *
     * @mbg.generated
     */
    public void setRequestType(Byte requestType) {
        this.requestType = requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.request_param
     *
     * @return the value of log_esb_request_resume.request_param
     *
     * @mbg.generated
     */
    public String getRequestParam() {
        return requestParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.request_param
     *
     * @param requestParam the value for log_esb_request_resume.request_param
     *
     * @mbg.generated
     */
    public void setRequestParam(String requestParam) {
        this.requestParam = requestParam == null ? null : requestParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.request_url
     *
     * @return the value of log_esb_request_resume.request_url
     *
     * @mbg.generated
     */
    public String getRequestUrl() {
        return requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.request_url
     *
     * @param requestUrl the value for log_esb_request_resume.request_url
     *
     * @mbg.generated
     */
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl == null ? null : requestUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.msg_id
     *
     * @return the value of log_esb_request_resume.msg_id
     *
     * @mbg.generated
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.msg_id
     *
     * @param msgId the value for log_esb_request_resume.msg_id
     *
     * @mbg.generated
     */
    public void setMsgId(String msgId) {
        this.msgId = msgId == null ? null : msgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.is_req_success
     *
     * @return the value of log_esb_request_resume.is_req_success
     *
     * @mbg.generated
     */
    public Byte getIsReqSuccess() {
        return isReqSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.is_req_success
     *
     * @param isReqSuccess the value for log_esb_request_resume.is_req_success
     *
     * @mbg.generated
     */
    public void setIsReqSuccess(Byte isReqSuccess) {
        this.isReqSuccess = isReqSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.is_need_callback_ack
     *
     * @return the value of log_esb_request_resume.is_need_callback_ack
     *
     * @mbg.generated
     */
    public Byte getIsNeedCallbackAck() {
        return isNeedCallbackAck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.is_need_callback_ack
     *
     * @param isNeedCallbackAck the value for log_esb_request_resume.is_need_callback_ack
     *
     * @mbg.generated
     */
    public void setIsNeedCallbackAck(Byte isNeedCallbackAck) {
        this.isNeedCallbackAck = isNeedCallbackAck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.is_callback_ack
     *
     * @return the value of log_esb_request_resume.is_callback_ack
     *
     * @mbg.generated
     */
    public Byte getIsCallbackAck() {
        return isCallbackAck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.is_callback_ack
     *
     * @param isCallbackAck the value for log_esb_request_resume.is_callback_ack
     *
     * @mbg.generated
     */
    public void setIsCallbackAck(Byte isCallbackAck) {
        this.isCallbackAck = isCallbackAck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.is_callback_ack_success
     *
     * @return the value of log_esb_request_resume.is_callback_ack_success
     *
     * @mbg.generated
     */
    public Byte getIsCallbackAckSuccess() {
        return isCallbackAckSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.is_callback_ack_success
     *
     * @param isCallbackAckSuccess the value for log_esb_request_resume.is_callback_ack_success
     *
     * @mbg.generated
     */
    public void setIsCallbackAckSuccess(Byte isCallbackAckSuccess) {
        this.isCallbackAckSuccess = isCallbackAckSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.callback_ack_date
     *
     * @return the value of log_esb_request_resume.callback_ack_date
     *
     * @mbg.generated
     */
    public Date getCallbackAckDate() {
        return callbackAckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.callback_ack_date
     *
     * @param callbackAckDate the value for log_esb_request_resume.callback_ack_date
     *
     * @mbg.generated
     */
    public void setCallbackAckDate(Date callbackAckDate) {
        this.callbackAckDate = callbackAckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.callback_ack_url
     *
     * @return the value of log_esb_request_resume.callback_ack_url
     *
     * @mbg.generated
     */
    public String getCallbackAckUrl() {
        return callbackAckUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.callback_ack_url
     *
     * @param callbackAckUrl the value for log_esb_request_resume.callback_ack_url
     *
     * @mbg.generated
     */
    public void setCallbackAckUrl(String callbackAckUrl) {
        this.callbackAckUrl = callbackAckUrl == null ? null : callbackAckUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.is_need_auto_retry
     *
     * @return the value of log_esb_request_resume.is_need_auto_retry
     *
     * @mbg.generated
     */
    public Byte getIsNeedAutoRetry() {
        return isNeedAutoRetry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.is_need_auto_retry
     *
     * @param isNeedAutoRetry the value for log_esb_request_resume.is_need_auto_retry
     *
     * @mbg.generated
     */
    public void setIsNeedAutoRetry(Byte isNeedAutoRetry) {
        this.isNeedAutoRetry = isNeedAutoRetry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.retry_type
     *
     * @return the value of log_esb_request_resume.retry_type
     *
     * @mbg.generated
     */
    public Byte getRetryType() {
        return retryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.retry_type
     *
     * @param retryType the value for log_esb_request_resume.retry_type
     *
     * @mbg.generated
     */
    public void setRetryType(Byte retryType) {
        this.retryType = retryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.is_retrying
     *
     * @return the value of log_esb_request_resume.is_retrying
     *
     * @mbg.generated
     */
    public Byte getIsRetrying() {
        return isRetrying;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.is_retrying
     *
     * @param isRetrying the value for log_esb_request_resume.is_retrying
     *
     * @mbg.generated
     */
    public void setIsRetrying(Byte isRetrying) {
        this.isRetrying = isRetrying;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.is_retry_success
     *
     * @return the value of log_esb_request_resume.is_retry_success
     *
     * @mbg.generated
     */
    public Byte getIsRetrySuccess() {
        return isRetrySuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.is_retry_success
     *
     * @param isRetrySuccess the value for log_esb_request_resume.is_retry_success
     *
     * @mbg.generated
     */
    public void setIsRetrySuccess(Byte isRetrySuccess) {
        this.isRetrySuccess = isRetrySuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.retry_num
     *
     * @return the value of log_esb_request_resume.retry_num
     *
     * @mbg.generated
     */
    public Integer getRetryNum() {
        return retryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.retry_num
     *
     * @param retryNum the value for log_esb_request_resume.retry_num
     *
     * @mbg.generated
     */
    public void setRetryNum(Integer retryNum) {
        this.retryNum = retryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.create_date
     *
     * @return the value of log_esb_request_resume.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.create_date
     *
     * @param createDate the value for log_esb_request_resume.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_esb_request_resume.update_date
     *
     * @return the value of log_esb_request_resume.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_esb_request_resume.update_date
     *
     * @param updateDate the value for log_esb_request_resume.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}