server:
  port: 8080

mybatis:
  config-location: classpath:mybatis-config.xml        # mybatis配置文件所在路径
  type-aliases-package: com.carrey.demoshardingsphere.po         # 所有Entity别名类所在包
  mapper-locations: classpath:/mapping/*Mapper.xml #,classpath:/mapper/*Mapper.xml      # mapper映射文件

#mybatis-plus:
#  mapper-locations: classpath:/mapping/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  #  typeAliasesPackage: com.kunchi.stock.po;
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  # 配置真实数据源
spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://123.57.34.196:3306/ds0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    driver-class-name: com.mysql.jdbc.Driver
  shardingsphere:
    datasource:
      names: ds1,ds2
    # 配置第 1 个数据源
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://123.57.34.196:3306/ds0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
    # 配置第 2 个数据源
      ds2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://123.57.34.196:3306/ds1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
    sharding:
      # 配置分库策略
      default-database-strategy:
        inline:
          sharding-column: user_id
          algorithm-expression: ds$->{user_id}
      tables:
        log_esb_request_resume:
          actual-data-nodes: ds$->{1..2}.log_esb_request_resume
