package com.carrey.demoshardingsphere.dao;

import com.carrey.demoshardingsphere.po.LogEsbRequestResume;
import com.carrey.demoshardingsphere.po.LogEsbRequestResumeExample;
import com.carrey.demoshardingsphere.po.LogEsbRequestResumeWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LogEsbRequestResumeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    long countByExample(LogEsbRequestResumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    int deleteByExample(LogEsbRequestResumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    int insert(LogEsbRequestResumeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    int insertSelective(LogEsbRequestResumeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    List<LogEsbRequestResumeWithBLOBs> selectByExampleWithBLOBs(LogEsbRequestResumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    List<LogEsbRequestResume> selectByExample(LogEsbRequestResumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    LogEsbRequestResumeWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LogEsbRequestResumeWithBLOBs record, @Param("example") LogEsbRequestResumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LogEsbRequestResumeWithBLOBs record, @Param("example") LogEsbRequestResumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LogEsbRequestResume record, @Param("example") LogEsbRequestResumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LogEsbRequestResumeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LogEsbRequestResumeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_esb_request_resume
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LogEsbRequestResume record);
}