spring:
  datasource:
    url: jdbc:mysql://123.57.34.196:3306/spring-jpa-demo?characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        hbm2ddl:
